name: Staging Deploy

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: [stage]

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from devel branch to stage
        if: github.base_ref == 'stage'
        run: |
          if [[ "${{ github.head_ref }}" != "devel" ]]; then
            echo "Pull requests to the 'stage' branch must come from the 'devel' branch."
            exit 1
          fi
  
  deploy:
    needs: check-pr-source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.GH_SERVICE_ROLE }}
          aws-region: us-east-1
          audience: sts.amazonaws.com
          
      - name: Download build artifacts from S3
        run: aws s3 cp s3://build-artifacts-fullstack/build ./build --recursive

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://${{ github.base_ref }}-fullstack --delete
