name: Production Deploy

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [prod]

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if PR is from stage branch to prod
        run: |
          PR_FROM_STAGE=$(git log -1 --pretty=format:'%s' | grep -c 'Merge pull request.*from stage')
          if [ $PR_FROM_STAGE -eq 0 ]; then
            echo "Deployments to the 'prod' branch must come from the 'stage' branch."
            exit 1
          fi

  deploy:
    if: success()
    needs: check-pr-source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.GH_SERVICE_ROLE }}
          aws-region: us-east-1
          audience: sts.amazonaws.com
          
      - name: Download build artifacts from S3
        run: aws s3 cp s3://build-artifacts-fullstack/build ./build --recursive

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://prod-fullstack --delete
